import type { NodeResult, RiskState } from '../types';

const BADGE: Record<RiskState, string> = {
  RED: 'bg-red-900 text-red-200 border-red-500',
  YELLOW: 'bg-amber-900 text-amber-100 border-amber-500',
  GREEN: 'bg-green-900 text-green-200 border-green-500',
  UNKNOWN: 'bg-slate-700 text-slate-200 border-slate-400'
};

function short(id: string) {
  return id.includes(':') ? id.slice(id.indexOf(':') + 1) : id;
}

export default function NodeDetails({ node }: { node: NodeResult | null }) {
  if (!node) {
    return (
      <div className="p-4 text-sm text-slate-400">
        Select a component in the graph to see why it has its current state.
      </div>
    );
  }

  return (
    <div className="space-y-4 overflow-y-auto p-4 text-sm">
      <div>
        <div className="flex items-center gap-2">
          <span className={`rounded border px-2 py-0.5 text-xs font-semibold ${BADGE[node.state]}`}>
            {node.state}
          </span>
          {node.critical && (
            <span className="rounded border border-fuchsia-500 bg-fuchsia-950 px-2 py-0.5 text-xs">
              CRITICAL
            </span>
          )}
        </div>
        <h2 className="mt-2 text-lg font-semibold">{node.name}</h2>
        <p className="text-xs text-slate-400">{node.node_type.replace(/_/g, ' ')}</p>
      </div>

      <dl className="grid grid-cols-2 gap-2 text-xs">
        <dt className="text-slate-400">Impact</dt>
        <dd>{node.impact_type}</dd>
        <dt className="text-slate-400">Rule applied</dt>
        <dd className="font-mono text-[11px]">{node.rule_applied}</dd>
        <dt className="text-slate-400">Distance</dt>
        <dd>{node.distance ?? 'unreachable'}</dd>
        <dt className="text-slate-400">Parse status</dt>
        <dd>{node.parse_status}</dd>
        {node.min_edge_confidence !== null && (
          <>
            <dt className="text-slate-400">Min edge confidence</dt>
            <dd>{node.min_edge_confidence.toFixed(2)}</dd>
          </>
        )}
      </dl>

      {node.flags.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {node.flags.map((flag) => (
            <span
              key={flag}
              className="rounded bg-slate-800 px-2 py-0.5 font-mono text-[10px] text-slate-300"
            >
              {flag}
            </span>
          ))}
        </div>
      )}

      <section>
        <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">
          Evidence chain
        </h3>
        {node.path.length === 0 ? (
          <p className="text-xs text-slate-400">
            {node.impact_type === 'MODIFIED'
              ? 'This component is directly modified by the change.'
              : 'No dependency path was found from the change.'}
          </p>
        ) : (
          <ol className="space-y-2">
            {node.path.map((step, index) => (
              <li key={index} className="rounded border border-slate-700 bg-slate-900 p-2">
                <div className="font-mono text-[11px]">
                  {short(step.source)}{' '}
                  <span className="text-amber-400">--{step.relationship}--&gt;</span>{' '}
                  {short(step.target)}
                </div>
                <div className="mt-1 text-[11px] text-slate-400">
                  {step.source_file}:{step.line ?? '?'} · rule{' '}
                  <span className="font-mono">{step.rule_id}</span> · confidence{' '}
                  {step.confidence.toFixed(2)}
                  {step.dynamic && ' · runtime-resolved'}
                </div>
              </li>
            ))}
          </ol>
        )}
      </section>

      {node.security_findings.length > 0 && (
        <section>
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">
            Security findings
          </h3>
          <ul className="space-y-1">
            {node.security_findings.map((finding, index) => (
              <li key={index} className="rounded border border-red-800 bg-red-950 p-2 text-[11px]">
                <span className="font-semibold">{finding.severity}</span> · {finding.type} ·{' '}
                {finding.source}
                <div className="text-slate-300">{finding.description}</div>
              </li>
            ))}
          </ul>
        </section>
      )}

      {node.explanation && (
        <section>
          <h3 className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">
            Explanation
          </h3>
          <p className="text-xs text-slate-300">{node.explanation}</p>
          <p className="mt-1 text-[10px] text-slate-500">
            Generated by: {node.explanation_source}. Explanatory only — the state above comes
            from the dependency graph.
          </p>
        </section>
      )}

      {node.source_files.length > 0 && (
        <section>
          <h3 className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">
            Source
          </h3>
          <ul className="font-mono text-[11px] text-slate-300">
            {node.source_files.map((file) => (
              <li key={file}>{file}</li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
